name: kubo-bosh-lite

features:
  use_dns_addresses: true

releases:
- name: kubo-etcd
  version: 4
  url: https://github.com/pivotal-cf-experimental/kubo-etcd/releases/download/v4/kubo-etcd.4.tgz
  sha1: f94ab00d423765e2c740836788dc256caa1af014
- name: kubo
  version: latest
- name: docker
  version: 28.0.1
  url: https://bosh.io/d/github.com/cf-platform-eng/docker-boshrelease?v=28.0.1
  sha1: 448eaa2f478dc8794933781b478fae02aa44ed6b
stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: "3468.5"

instance_groups:
- name: etcd
  instances: 1
  networks:
  - name: &network-name default
  azs: [z1]
  jobs:
  - name: etcd
    release: kubo-etcd
    properties:
      etcd:
        require_ssl: false
        peer_require_ssl: false
  stemcell: trusty
  vm_type: common
  persistent_disk_type: 5120

- name: master
  instances: 1
  networks:
  - name: *network-name
    static_ips: [((kubernetes_master_host))]
  azs: [z1]
  jobs:
  - name: kubo-dns-aliases
    release: kubo
  - name: cloud-provider
    release: kubo
    properties: {}
  - name: flanneld
    release: kubo
  - name: kubernetes-api
    release: kubo
    properties:
      admin-username: admin
      admin-password: ((kubo-admin-password))
      kubelet-password: ((kubelet-password))
      backend_port: 8443 # Bosh links hack
      port: 8443
      authorization-mode: &authorization_mode rbac
      tls:
        kubernetes: ((tls-kubernetes))
  - name: kubeconfig
    release: kubo
    properties:
      kubelet-password: ((kubelet-password))
      tls:
        kubernetes: ((tls-kubernetes))
  - name: kubernetes-controller-manager
    release: kubo
    properties: {}
  - name: kubernetes-scheduler
    release: kubo
  - name: kubernetes-system-specs
    release: kubo
    properties:
      admin-username: admin
      admin-password: ((kubo-admin-password))
      authorization-mode: *authorization_mode
  stemcell: trusty
  vm_type: master

- name: worker
  instances: 3
  networks:
  - name: *network-name
  azs: [z1]
  jobs:
  - name: kubo-dns-aliases
    release: kubo
  - name: flanneld
    release: kubo
  - name: docker
    release: docker
    properties:
      docker:
        flannel: true
        iptables: false
        ip_masq: false
        log_level: error
        storage_driver: overlay
        default_ulimits: [ "nofile=65536" ]
      env: {}
  - name: kubeconfig
    release: kubo
    properties:
      kubernetes-api-url: "https://((kubernetes_master_host)):8443"
      kubelet-password: ((kubelet-password))
      tls:
        kubernetes: ((tls-kubernetes))
  - name: cloud-provider
    release: kubo
    properties: {}
  - name: kubelet
    release: kubo
    properties:
      tls:
        kubelet: ((tls-kubelet))
  - name: kubernetes-proxy
    release: kubo
  stemcell: trusty
  vm_type: worker
  persistent_disk_type: 10240

update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 10000-300000
  update_watch_time: 10000-300000

variables:
- name: kubo-admin-password
  type: password
- name: kubelet-password
  type: password
- name: kubo_ca
  type: certificate
  options:
    is_ca: true
    common_name: ca
- name: tls-kubelet
  type: certificate
  options:
    ca: kubo_ca
    common_name: ((kubernetes_master_host))
    alternative_names: [((kubernetes_master_host))]
    organization: "system:nodes"
- name: tls-kubernetes
  type: certificate
  options:
    ca: kubo_ca
    organization: "system:masters"
    common_name: ((kubernetes_master_host))
    alternative_names:
    - ((kubernetes_master_host))
    - 10.100.200.1
    - kubernetes
    - kubernetes.default
    - kubernetes.default.svc
    - kubernetes.default.svc.cluster.local
    - master.kubo
